export { default as Home } from './Home/Home'
export { default as Profile } from './Profile/Profile'
export { default as Admin } from './Admin/Admin'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as Setting } from './Setting/Setting'
