export { default as Home } from './Home/Home'
export { default as Profile } from './Profile/Profile'
export { default as Admin } from './Admin/Admin'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as ManageQuestion } from './ManageQuestion/ManageQuestion'
export { default as ManageQuiz } from './ManageQuiz/ManageQuiz'
export { default as ManageUser } from './ManageUser/ManageUser'
