export { default as Home } from './Home/Home'
export { default as Profile } from './Profile/Profile'
export { default as Admin } from './Admin/Admin'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as ManageQuestion } from './Admin/ManageQuestion'
export { default as ManageQuiz } from './Admin/ManageQuiz'
export { default as ManageUser } from './Admin/ManageUser'
